// Client-side Word export. Builds a Word-compatible HTML document and
// downloads it as a .doc file — no backend, no external libraries.

function esc(s = "") {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function statusText(r) {
  if (r.status === "accepted") return "Accepted";
  if (r.status === "rejected") return "Rejected";
  if (r.weak) return "Needs evidence";
  return "Pending";
}

export function exportToWord(rows, session) {
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const rowsHtml = rows
    .map(
      (r) => `
      <tr>
        <td style="border:1px solid #d1d5db;padding:8px 10px;vertical-align:top;font-family:'Courier New',monospace;font-weight:bold;color:#4f46e5;">${esc(
          r.element
        )}</td>
        <td style="border:1px solid #d1d5db;padding:8px 10px;vertical-align:top;">${esc(
          r.claimText
        )}</td>
        <td style="border:1px solid #d1d5db;padding:8px 10px;vertical-align:top;">${esc(
          r.evidence
        )}</td>
        <td style="border:1px solid #d1d5db;padding:8px 10px;vertical-align:top;">${esc(
          r.reasoning
        )}</td>
        <td style="border:1px solid #d1d5db;padding:8px 10px;vertical-align:top;text-align:center;">${esc(
          statusText(r)
        )}</td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8" />
  <title>Patent Claim Chart</title>
  <!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml><![endif]-->
</head>
<body style="font-family:'Calibri',Arial,sans-serif;color:#111827;">
  <h1 style="font-size:22px;margin:0 0 4px;">Patent Claim Chart</h1>
  <p style="color:#6b7280;margin:0 0 2px;font-size:12px;">Refined with ClaimForge · ${esc(
    date
  )}</p>
  <p style="color:#6b7280;margin:0 0 16px;font-size:12px;">
    Claim chart: ${esc(session?.claimChart?.name || "claim-chart.xlsx")} &nbsp;|&nbsp;
    Documentation: ${esc(session?.productDocs?.name || "product-docs.pdf")}
  </p>
  <table style="border-collapse:collapse;width:100%;font-size:12px;">
    <thead>
      <tr style="background:#4f46e5;color:#ffffff;">
        <th style="border:1px solid #4f46e5;padding:8px 10px;text-align:left;">Element</th>
        <th style="border:1px solid #4f46e5;padding:8px 10px;text-align:left;">Patent Claim</th>
        <th style="border:1px solid #4f46e5;padding:8px 10px;text-align:left;">Evidence</th>
        <th style="border:1px solid #4f46e5;padding:8px 10px;text-align:left;">AI Reasoning</th>
        <th style="border:1px solid #4f46e5;padding:8px 10px;text-align:left;">Status</th>
      </tr>
    </thead>
    <tbody>${rowsHtml}</tbody>
  </table>
  <p style="color:#9ca3af;margin-top:16px;font-size:11px;">
    Generated by ClaimForge — AI Patent Claim Chart Refinement (demo). Evidence and reasoning are illustrative.
  </p>
</body>
</html>`;

  const blob = new Blob([html], { type: "application/msword;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `claim-chart-refined-${new Date()
    .toISOString()
    .slice(0, 10)}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
